### ISSUE TITLE
Code not working for Revit model with 2nd floor 

### ISSUE THREAD

**Issue by antonszilasi** [ladybug-analysis-tools/honeybee-plus#22] opened 2016-08-10 14:23 UTC
I added a 2nd floor with 3 rooms to the Revit model that was working well this my commit - https://github.com/antonszilasi/honeybeex/commit/b9b094c910861ead7bc4bb6e838cb36b31138d32

Now I am getting the error below.

ERROR:
Invalid structure for input points: (None,)

If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybeex/issues

Traceback (most recent call last):
  File "<string>", line 42, in <module>
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\revit.py", line 325, in convertRoomsToHBZones
    _hbfenSurface = HBFenSurface(
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\hbfensurface.py", line 29, in __init__
    FenSurface.**init**(self, name, sortedPoints=sortedPoints,
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\honeybee\hbfensurface.py", line 50, in **init**
    HBAnalysisSurface.**init**(self, name, sortedPoints=sortedPoints,
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\honeybee_hbanalysissurface.py", line 49, in **init**
    self.points = sortedPoints
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\honeybee_hbanalysissurface.py", line 257, in points
    self.addPointList(pts, True)
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\honeybee_hbanalysissurface.py", line 300, in addPointList
    raise ValueError('Invalid structure for input points: {}'.format(pts))
ValueError: Invalid structure for input points: (None,)

For some reason the extractPanelVertices function is returning (None,) causing this error I have attached the new Revit file here: https://github.com/antonszilasi/honeybeex/commit/5cc1818289f5fb7cb7442f5d7f6cecb97d0cc56a

**Comment by mostaphaRoudsari** [comment] 2016-08-18 22:58
@antonszilasi thank you for reporting all the issues and providing the code and the files. I will check them next week and report back. :100:

**Comment by mostaphaRoudsari** [comment] 2017-01-18 13:59
We're not going to use this method anyways so I'm closing the related issues that I cannot reproduce.

**Closed** 2017-01-18 13:58 UTC
Labels: bug
