### ISSUE TITLE
Generate Test Points from HBZones not working for 2nd floor

### ISSUE THREAD

**Issue by antonszilasi** [ladybug-analysis-tools/honeybee-plus#19] opened 2016-07-25 16:27 UTC
Script works for room number 1 and 2 however when room number 3 and 4 is entered it fails with the following error in the Generate Test Points from HBZones component

![capture](https://cloud.githubusercontent.com/assets/8773483/17108834/cf8cd7be-525a-11e6-9cfb-97e898c356a1.JPG)

ERROR:
Unable to slice bodies : BULLETIN_NOT_ON_BOARD -- remove bulletin from bulletin board it was not on

If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybeex/issues

Traceback (most recent call last):
  File "<string>", line 56, in <module>
  File "C:\Users\szilasia\AppData\Roaming\Dynamo\Dynamo Revit\1.1\packages\Honeybee\extra\honeybeex\geometryoperation.py", line 406, in _GridGenerator__createGrids
    if border.ContainmentTest(_cenPoint):
StandardError: Unable to slice bodies : BULLETIN_NOT_ON_BOARD -- remove bulletin from bulletin board it was not on

The Revit file can be found here:

https://app.box.com/files/0/f/0/1/f_76623642845

**Comment by antonszilasi** [comment] 2016-08-01 18:00
Update: Strangely I cannot reproduce this error

**Comment by mostaphaRoudsari** [comment] 2016-08-18 23:06
This looks like a dynamo issue but I keep it open so I can take a look.

**Comment by mostaphaRoudsari** [comment] 2016-11-22 16:07
I can't reproduce this error. I'm going to close it for now.

**Closed by mostaphaRoudsari** 2016-11-22 16:07 UTC
Labels: bug
